name: Generate Snake Animation
permissions:
  contents: write

on:
  schedule:
    - cron: "0 */12 * * *"   # a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Heverald0
          outputs: dist/github-contribution-grid-snake.svg

      - name: Prepare output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Ensure we have dist
          ls -la dist || (echo "dist not found" && exit 1)
          # Create a clean tree and copy dist contents to the root
          git fetch origin output || true
          if git show-ref --verify --quiet refs/heads/output; then
            git checkout output
            git rm -rf .
          else
            git checkout --orphan output
            git rm -rf .
          fi
          cp -r ../$(pwd | sed 's#^.*/##')/dist/* . 2>/dev/null || cp -r dist/* .
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update snake animation"
            git push origin HEAD:output --force
          fi
