name: Generate Snake

on:
  schedule:
    # Gera todo dia às 00:00 (UTC)
    - cron: "0 0 * * *"
  workflow_dispatch:  # Permite rodar manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobrinha 🐍
        uses: Platane/snk@v3
        with:
          github_user_name: HeveraldoAugusto  # 🔁 coloque seu nome de usuário exato do GitHub
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake-neon.svg?color_snake=#39FF14&color_dots=#0D1117

      - name: Enviar resultado para o branch de saída
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
