name: Generate Snake 🐍

on:
  schedule:
    - cron: "0 0 * * *"   # Executa todo dia à 00:00 (UTC)
  workflow_dispatch:       # Permite rodar manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clona o repositório
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # 2️⃣ Gera a animação da cobrinha (tema escuro + neon)
      - name: Gerar animação da cobrinha 🐍
        uses: Platane/snk@v3
        with:
          github_user_name: Heverald0
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#00FF88&color_dots=#0D1117&color_empty=#1E1E1E&color_completed=#00FF88
            dist/github-contribution-grid-snake-neon.svg?color_snake=#39FF14&color_dots=#0D1117&color_empty=#1E1E1E

      # 3️⃣ Envia o resultado para o branch "output"
      - name: Enviar resultado para o branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 4️⃣ Lista os arquivos gerados (para depuração)
      - name: Listar arquivos gerados
        run: ls -la dist
