name: Generate Snake 🐍

on:
  schedule:
    - cron: "0 0 * * *"   # Executa todo dia à 00:00 (UTC)
  workflow_dispatch:       # Permite rodar manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clona o repositório
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # 2️⃣ Gera a animação da cobrinha (tema escuro + neon colorido)
      - name: Gerar animação da cobrinha 🐍
        uses: Platane/snk@v3
        with:
          github_user_name: Heverald0
          outputs: |
            dist/github-contribution-grid-snake-colored.svg?palette=github-dark&color_snake=#39FF14&color_dots=#39FF14,#00FFFF,#FF00FF,#FFEA00,#FF007F&color_empty=#0A0A0A
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#00FF88&color_dots=#00FF88&color_empty=#1E1E1E
            dist/github-contribution-grid-snake-neon.svg?palette=github-dark&color_snake=#39FF14&color_dots=#00FF88&color_empty=#0D1117

      # 3️⃣ Envia o resultado para o branch de saída (output)
      - name: Enviar resultado para o branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 4️⃣ Mostra logs dos arquivos gerados (opcional)
      - name: Listar arquivos gerados
        run: ls -la dist
